# Site settings
title: Jesse P Lesperance
twitter_username: jlesperance
name: Jesse P Lesperance

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Home/Blog
   url: https://lesperance.io
 - title: GitHub
   url: https://github.com/jplesperance
 - title: LinkedIn
   url: https://www.linkedin.com/in/jesseplesperance

#Any buzzword skills you want to include
skills:
 - Cloud Security
 - Configuration Management(Ansible, Puppet, SaltStack)
 - Process Automation
 - Kubernetes/Istio
 - Cryptography
 - Microservices
 - DevOps/DevSecOps
 - Continuous Integration
 - Network/Data/Infrastructure Security
 - DFIR
 - Network Penetration Testing
 - Wireless Security
 - Reverse Engineering
 - Programming(Python, Golang, Bash)

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://lesperance.io/feed.xml

#Work experience is required
roles:
 - title: Member of Advisory Board
   start: 06/20
   end: Ongoing
   employer: CionSystems
   description: Advisor
 - title: Member of Advisory Board
   start: 06/20
   end: Ongoing
   employer: Cuemby
   description: Advisor
 - title: Senior Security Architect
   start: 01/18
   end: Ongoing
   employer: Evernote
   description: Responsible for Infrastructure, Network and Data Security<br />
    - Create and Socialize Security Policies to the Technical Operations and Engineering teams<br />
    - Conduct security reviews on new cloud products<br />
    - Review all infrastructure, data and network components of all software and design documentation<br />
    - Refactored IAM usage from a broad access model down to a least privileged model<br />
    - Create a data catalog, with data classifications<br />
    - Create and document threat models, and determine the needed controls to minimize risks to an acceptable level<br />
    - Setup tools to scan the Cloud infrastructure against a set of security policies and alert on violations<br />
    - Audit the cloud infrastructure and IAM implementations to ensure defined policies and approved patterns are continuously being followed<br />
    - Work with Tech Ops and Engineering to define new patterns that meet the organization's security policies and goals as needed<br />
    - Defined a secure and auditable secret management solution and policy; provided a roadmap of how the Tech Ops team should implement the solution to minimize engineers ability to see all secrets<br />
    - Defined a Kubernetes Security Maturity roadmap to help improve the security posture of all microservices deployments and help ensure a least privileged model<br />
    - Led the infrastructure and security sub-teams for designing and standing up a new Kubernetes cluster with the Istio Service Mesh<br />
 - title: Senior DevOps Engineer
   start: 04/16
   end: 12/17
   employer: eBay Inc
   description: Lead on the Enterprise Security Operations and Development team.<br />Responsibilities include:<br />
    - Implementation and administration of SaltStack for State Management and command channels<br />
    - Implementation and administration of Nagios XI for system and service monitoring<br />
    - Hardening of Infrastructure<br />
    - Manage Secret/key Management infrastructure that support revenue<br />
    - Patching of infrastructure<br />
    - Performing BCDR excercises<br />
    - Develop tools for process automation<br />
    - eBay Agile Leader<br />
    - eBay Privacy Champion<br />
    - eBay Security Champion<br />
    - Led a cross-function Cryptography team<br />
 - title: Manager of DevOps
   start: 03/15
   end: 04/16
   employer: Apixio Inc
   description: Work on the Technical Operations Team.<br />
    - Used Ansible to create a reusable/extensible application deployment framework for deploying applications into AWS EC2<br />
    - Handled coordinating Vulnerability scans and vulnerability remediation of cloud applications on AWS in a HIPPA environment<br />
    - Achieved PCI Certification on production infrastructure through issue/vulnerability remediation<br />
    - Implemented SaltStack to handle AWS ec2 server config management<br />
    - Implemented Terraform to handle AWS Cloud Infrastructure State<br />
    - Utilized Terraform and docker to create a dynamic development environment<br />
    - Designed and implemented SSH Key management system for our AWS VPC environments<br />
    - Designed and implemented aws ec2 Security Group management system to handle managing AWS security groups rules<br />
    - Deployed a Mesosphere cluster into AWS and created a container infrastructure to allow for more flexible options with having multiple versions of the same microservice in operation at the same time<br />
    - Implemented Service Discovery, Centralized config management and Secret mamangement systems in AWS for creating a better security posture.<br />
 - title: IT Operations Manager
   start: 11/12
   end: 01/15
   employer: Hortonworks Inc
   description: Came in as the first member of the IT Operations team. Handled SysOps, DevOps, NetOps and SecOps tasks. Setup all core company server infrastructure and currentCame in as the first member of the IT Operations team. Handled SysOps, DevOps, NetOps and SecOps tasks. Setup all core company server infrastructure and current support and maintain all infrastructure. Built a team of 5 Sys Admins and 2 Network Engineers.<br />
    - Created new corporate servers and services as part of the building move(DNS, LDAP, NTP, Radius, Rancid, Zabbix. Deployed all applications using Docker<br />
    - Implemented Kickstart for bare-metal provisioning until we were able to get BCFG2/Ansible in place.
    - Handle all security related functions including, badging, managing camera and security network, defining IT processes(AUP, password policies, etc.), On-boarding(Account creation), Off-board(Account suspension/deletion), review device and server logs to identify possible issues, litigation searches, server hardening, identifying security holes and recommending fixes. Setting up IDS and behavioral analysis tools<br />
    - Manage various IT Operations based projects and worked with stakeholders from gathering requirements through delivery.<br />
    - Review all RFCs submitted to the Change/Release Advisory Board, perform initial review of request and classification of request. Also responsible for determining if RFCs are approved, rejected or tabled<br />
    - Manage all corporate SAS solutions(Jira, Box.com, Github, Confluence, etc.)<br />
    - Work with the Operations team to constantly review processes and infrastructure to see where improvements can be made<br />
    - Implemented Zabbix and Nagios as our server monitoring solutions.<br /> 
    - Built a team of 5 Sys Admins and 2 Network Engineers.<br />
 - title: Sr DevOps Engineer
   start: 05/12
   end: 10/12
   employer: Accelerator Inc
   description: Worked in the Developer Operations group within IT
    - Refactored portions of the web application resulting in both a 40% reduction in code and a more flexible configuration
    - Administered and maintained critical applications like Confluence, Jira and Jenkins
    - Lead for a site migrations from Zend Framework to Wordpress
    - Managed an outsourced design team in the redesign of the company's web properies
 - title: Director of Engineering
   start: 05/10
   end: 12/11
   employer: Ricoh EWS
   description: Joined as a Lead Software Engineer, the companies first engineering hire, promoted to Engineering Manager a short time after and to Director of Engineering a year later.
    - Recruited and hired a team of 15 software engineers.  10 Backend PHP/Java engineers and 5 Frontend engineers
    - Architected and built a RESTful SaaS web service for their electonic document workflow offering.
    - Mentored and promoted 2 engineers into management and created an SDK Development/Professional Services team
    - Architected the cloud based environment for hosting the SaaS offering in AWS, with failover and scalability adopting a hybrid cloud model
 - title: Senior Software Engineer
   start: 09/08
   end: 05/10
   employer: CNET/CBS Interactive
   description: Worked with a small team to develop and maintain one of the largets video/community sites on the internet at the time, TV.com
    - Created a Unified Video Infrastructure that ingested videos from partners, normalizws the data and redistributes the videos out to partners
    - Create various tools for analyzing site performance and indentify performance bottlenecks
    - Created the TV.com HD Video Gallery
 - title: Senior Software Architect
   start: 04/08
   end: 09/08
   employer: Zend Technologies
   description: Worked as one of two Technical Consultants for North America
    - Attended pre-sales meetings with clients and partners to gather information and determine the type of consulting services needed
    - Conducted Webinars and on-site training on topics like Unit Testing, Continuous Integration, Application Security and Zend Framework usage
    - Traveled to customer and partner sites to provide training, consulting and application development
 - title: Director of Technology
   start: 10/07
   end: 04/08
   employer: Pickpal
   description: Managed the engineering team and companies compute infrastructure
    - Hired and managed a team of engineers, designers and system admins
    - Designed a sports wagering application framework that allowed for the easy lauch of 36 team rival sites based on theming and configuration changes
    - Architected a server/application architecture to handle 10,000 concurrent connections per second
 - title: Senior Web Developer
   start: 06/06
   end: 10/07
   employer: VMWare
   description: Worked closely with the web marketing team and the techinical network team
    - Developed the Virtual Appliance Marketplace
    - Supported the VMWare Technical Network and helped migrate from a forum based site to a community based site
    - Took ownership of the code deployment process and refactored the legacy deployment architecture into a more robust architecture that allowed roll back without another deployement
    - Created the initial(pre-SFDC) VMWare Partner Portal
 - title: Lead Developer
   start: 01/00
   end: 05/06
   employer: Wiscasset Web Development
   description: Responsible for consulting with potential clients
    - Managed a team of 6 developers
    - Mentored and handled code reviews for junior and mid-level engineers
    - Created Technical and End-user documentation
    - Worked with clients directly for periodic code drops and final milestone deliveries

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 1999
   subject: Computer Science
   school: Arizona State University

#List of interesting Github repo/projects to include - optional
github:
 - jplesperance/redis-sniffer
 - jplesperance/redis-replay
 - jplesperance/tcn
 - jplesperance/security-tools

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/1433057/jesse-p-lesperance
   flairimageurl: https://stackoverflow.com/users/flair/1433057.png

coursera:
  courses:
    - title: WiFi Security Basics
      badge: https://api.accredible.com/v1/frontend/credential_website_embed_image/badge/14222590
      link: https://www.credential.net/019ca699-855c-4d1e-8007-500678dd18ea
      date: 11/28/2019
    - title: Password Cracking Basics
      badge: https://api.accredible.com/v1/frontend/credential_website_embed_image/badge/16889893
      link: https://www.credential.net/97159ac7-f801-492f-9ecc-dfbdb0a4a813
      date: 3/23/2020

isc2:
  courses:
    - title: Introduction to Memory Analysis with Volatility
      type: Lab Course
      date: 2/13/2020

certifications:
  courses:
    - title: Offensive Security Wireless Professional
      earned: 5/19/2019
      exires: N/A
      org: Offensive Secuirty
      link:
    - title: Junior Penetration Tester
      earned: 5/26/2019
      expires: N/A
      org: eLearn Security
      link:
    - title: Certified Information Systems Auditor
      earned: 5/17/2017
      expires: 12/31/2021
      org: ISACA
      link:
    - title: Certified Cloud Security Professional
      earned:
      expires:
      org: (ISC)2
      link:

intro: |
  Experienced Information Security hands on technology leader with a demonstrated security, vulnerability management & penetration testing accomplishments, specializing in cloud security. Areas of expertise include: Enterprise Software, Regulator Compliance, Application Security, Identity and Access Management, Cloud Security, Container Security, Enterprise Architecture, DevSecOps, Pen Testing, Encryption/PKI and Infrastructure Architecture. <br /><br />
  An accomplished professional with over 10+ years of diverse IT experience in the fields of Software Engineering, Information Security Architecture, Network Architecture, Program Management, Technical Operations and Enterprise Solutions Architecture. <br/><br/>
  Creative problem solver and strategic decision maker in fast-paced fluid and cross functional environments. 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  <strong>Information Security</strong> I currently work as a Senior Security Architect for Evernote.  I am the singular Security Architect in the organization, and handle Network, Data and Cloud Security<br />
  <strong>DevOps/DevSecOps</strong> I have over a decade of DevOps experience including, CI/CD, Infr as Code, Configuration Management(Ansible, Puppet and SaltStack), Server Management, Monitoring and automation<br /><br /> 
  I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://lesperance.io/">lesperance.io</a>
