# Site settings
title: Jesse P Lesperance
twitter_username: jlesperance
name: Jesse P Lesperance

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://lesperance.io
 - title: GitHub
   url: https://github.com/jplesperance
 - title: LinkedIn
   url: https://www.linkedin.com/in/jesseplesperance

#Any buzzword skills you want to include
skills:
 - Cloud Security
 - Kubernetes/Istio
 - Cryptography
 - Microservices
 - DevOps
 - Continuous Integration
 - Network/Data/Infrastructure Security
 - DFIR
 - Network Penetration Testing
 - Wireless Security

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://lesperance.io/feed.xml

#Work experience is required
roles:
 - title: Senior Security Architect
   start: 2018
   end: Ongoing
   employer: Evernote
   description: Responsible for Infrastructure, Network and Data Security
    - Create and Socialize Security Policies to the Technical Operations and Engineering teams
    - Conduct security reviews on new cloud products
    - Review all infrastructure, data and network components of all software and design documentation
    - Refactored IAM usage from a broad access model down to a least privileged model
    - Create a data catalog, with data classifications
    - Create and document threat models, and determine the needed controls to minimize risks to an acceptable level
    - Setup tools to scan the Cloud infrastructure against a set of security policies and alert on violations
    - Audit the cloud infrastructure and IAM implementations to ensure defined policies and approved patterns are continuously being followed
    - Work with Tech Ops and Engineering to define new patterns that meet the organization's security policies and goals as needed
    - Defined a secure and auditable secret management solution and policy; provided a roadmap of how the Tech Ops team should implement the solution to minimize engineers ability to see all secrets
    - Defined a Kubernetes Security Maturity roadmap to help improve the security posture of all microservices deployments and help ensure a least privileged model
    - Led the infrastructure and security sub-teams for designing and standing up a new Kubernetes cluster with the Istio Service Mesh

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 1999
   subject: Computer Science
   school: Arizona State University

#List of interesting Github repo/projects to include - optional
github:
 - jplesperance/redis-sniffer
 - jplesperance/redis-replay
 - jplesperance/tcn

#Stackoverflow flair is optional
stackoverflow:
   profileurl: http://stackoverflow.com/users/258813/rhinds
   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
Experienced Information Security Professional with a demonstrated history working in the health care industry and specializing in Cloud Security. Areas of expertise include: Enterprise Software, Regulator Compliance, Application Security, Identity and Access Management, Cloud Security, Container Security, Enterprise Architecture, DevSecOps, Pen Testing, Encryption/PKI and Infrastructure Architecture.
<br/><br/>
An accomplished professional with over 20 years of diverse IT experience in the fields of Software Engineering, Information Security Architecture, Network Architecture, Program Management, Technical Operations and Enterprise Solutions Architecture.
<br/><br/>
Creative problem solver and strategic decision maker in fast-paced fluid environments. 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="http://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="http://projects.spring.io/spring-social/">http://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://lesperance.io/">lesperance.io</a>
