# Site settings
title: Jesse P Lesperance
twitter_username: jlesperance
name: Jesse P Lesperance

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://lesperance.io
 - title: GitHub
   url: https://github.com/jplesperance
 - title: LinkedIn
   url: https://www.linkedin.com/in/jesseplesperance

#Any buzzword skills you want to include
skills:
 - Cloud Security
 - Kubernetes/Istio
 - Cryptography
 - Microservices
 - DevOps
 - Continuous Integration
 - Network/Data/Infrastructure Security
 - DFIR
 - Network Penetration Testing
 - Wireless Security

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://lesperance.io/feed.xml

#Work experience is required
roles:
 - title: Senior Security Architect
   start: 01/18
   end: Ongoing
   employer: Evernote
   description: Responsible for Infrastructure, Network and Data Security<br />
    - Create and Socialize Security Policies to the Technical Operations and Engineering teams<br />
    - Conduct security reviews on new cloud products<br />
    - Review all infrastructure, data and network components of all software and design documentation<br />
    - Refactored IAM usage from a broad access model down to a least privileged model<br />
    - Create a data catalog, with data classifications<br />
    - Create and document threat models, and determine the needed controls to minimize risks to an acceptable level<br />
    - Setup tools to scan the Cloud infrastructure against a set of security policies and alert on violations<br />
    - Audit the cloud infrastructure and IAM implementations to ensure defined policies and approved patterns are continuously being followed<br />
    - Work with Tech Ops and Engineering to define new patterns that meet the organization's security policies and goals as needed<br />
    - Defined a secure and auditable secret management solution and policy; provided a roadmap of how the Tech Ops team should implement the solution to minimize engineers ability to see all secrets<br />
    - Defined a Kubernetes Security Maturity roadmap to help improve the security posture of all microservices deployments and help ensure a least privileged model<br />
    - Led the infrastructure and security sub-teams for designing and standing up a new Kubernetes cluster with the Istio Service Mesh<br />
 - title: Senior DevOps Engineer
   start: 04/16
   end: 12/17
   employer: eBay Inc
   description: Lead on the Enterprise Security Operations and Development team.<br />Responsibilities include:<br />
    - Implementation and administration of SaltStack for State Management and command channels<br />
    - Implementation and administration of Nagios XI for system and service monitoring<br />
    - Hardening of Infrastructure<br />
    - Manage Secret/key Management infrastructure that support revenue<br />
    - Patching of infrastructure<br />
    - Performing BCDR excercises<br />
    - Develop tools for process automation<br />
    - eBay Agile Leader<br />
    - eBay Privacy Champion<br />
    - eBay Security Champion<br />
    - Led a cross-function Cryptography team<br />
 - title: Manager of DevOps
   start: 03/15
   end: 04/16
   employer: Apixio Inc
   description: Work on the Technical Operations Team.<br />
   #    - Used Ansible to create a reusable/extensible application deployment framework for deploying applications into AWS EC2<br />
   # - Handled coordinating Vulnerability scans and vulnerability remediation of cloud applications on AWS in a HIPPA environment<br />
   # - Achieved PCI Certification on production infrastructure through issue/vulnerability remediation<br />
   # - Implemented SaltStack to handle AWS ec2 server config management<br />
   # - Implemented Terraform to handle AWS Cloud Infrastructure State<br />
   # - Utilized Terraform and docker to create a dynamic development environment<br />
   # - Designed and implemented SSH Key management system for our AWS VPC environments<br />
   # - Designed and implemented aws ec2 Security Group management system to handle managing AWS security groups rules<br />
   # - Deployed a Mesosphere cluster into AWS and created a container infrastructure to allow for more flexible options with having multiple versions of the same microservice in operation at the same time<br />
   # - Implemented Service Discovery, Centralized config management and Secret mamangement systems in AWS for creating a better security posture.<br />

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 1999
   subject: Computer Science
   school: Arizona State University

#List of interesting Github repo/projects to include - optional
github:
 - jplesperance/redis-sniffer
 - jplesperance/redis-replay
 - jplesperance/tcn

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/1433057/jesse-p-lesperance
   flairimageurl: https://stackoverflow.com/users/flair/1433057.png

intro: |
  Experienced Information Security Professional with a demonstrated history working in the health care industry and specializing in Cloud Security. Areas of expertise include: Enterprise Software, Regulator Compliance, Application Security, Identity and Access Management, Cloud Security, Container Security, Enterprise Architecture, DevSecOps, Pen Testing, Encryption/PKI and Infrastructure Architecture. <br /><br />
  An accomplished professional with over 20 years of diverse IT experience in the fields of Software Engineering, Information Security Architecture, Network Architecture, Program Management, Technical Operations and Enterprise Solutions Architecture. <br/><br/>
  Creative problem solver and strategic decision maker in fast-paced fluid environments. 

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  <strong>Information Security</strong> I currently work as a Senior Security Architect for Evernote.  I am one of 2 Security Architects in the organization, and handle Network, Data 
  I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://lesperance.io/">lesperance.io</a>
